### ISSUE TITLE
nupdate implementation

### ISSUE THREAD

**Issue by dhruvramdev** [pranaylikhitkar/Scripting#1]
Current Implementation Can Be Improved By Employing a 24 hrs or 6hrs Cron Job Instead of do while every 5 sec. Updates will be never this often.

**Comment by pranaylikhitkar** [comment]
I agree. In fact I am using crontab. But it was a last minute idea that I came with up for this script. 
`29 19 * * * /usr/local/bin/nupdate`
This command in crontab -e runs the script everyday at 07:29 pm. And creates Logs as well.
Will update. Cheers.

**Comment by pranaylikhitkar** [comment]
I think adding crontab job manually will be much more helpful then adding it to the script. Just execute this in your terminal. But I have some concerns regarding root permissions with this method.
`crontab -l | { cat; echo "29 19 * * * <path-to-nupdate-script>"; } | crontab -`
Another way can be : 
_Open crontab_
`sudo crontab -e`
_Add below lines to crontab after choosing your favourite editor_
`29 19 * * * <path-to-nupdate-script>`
This should help. Moreover I also increased sleep time in the script.
